### ISSUE TITLE
Find the sources of the conflicts with most recent version of epiprocess

### ISSUE THREAD

**Issue by rachlobay** [cmu-delphi/epipredict#104]
In DESCRIPTION, had to change the version of epiprocess used to to older version dajmcdon/epiprocess else many errors like [these from this R CMD Check](https://github.com/cmu-delphi/epipredict/runs/7399765068?check_suite_focus=true) are encountered. Possibly due to `[.epi_df` that was introduced in epiprocess. Should try to find the sources of the conflicts with the most recent version of epiprocess that is available on Github.

**Comment by mgyliu** [comment]
I put a `browser()` in `epi_shift.R:epi_shift_single` and ran `devtools::test()`. This should be coming from the last test in `tests/testthat/test-step_epi_shift.R`

```
Browse[1]> x
An `epi_df` object, 20,496 x 4 with metadata:
* geo_type  = state
* time_type = day
* as_of     = 2022-05-31 12:08:25

# A tibble: 20,496 x 4
   geo_value time_value case_rate death_rate
 * <chr>     <date>         <dbl>      <dbl>
 1 ak        2020-12-31      35.9      0.158
 2 al        2020-12-31      65.1      0.438
 3 ar        2020-12-31      66.0      1.27 
 4 as        2020-12-31       0        0    
 5 az        2020-12-31      76.8      1.10 
 6 ca        2020-12-31      96.0      0.751
 7 co        2020-12-31      35.8      0.649
 8 ct        2020-12-31      52.1      0.819
 9 dc        2020-12-31      31.0      0.601
10 de        2020-12-31      65.2      0.807
# ... with 20,486 more rows
# i Use `print(n = ...)` to see more rows
Browse[1]> x %>%
+     dplyr::select(tidyselect::all_of(c(key_cols, col)))
An `epi_df` object, 20,496 x 3 with metadata:
* geo_type  = state
* time_type = day
* as_of     = 2022-05-31 12:08:25

# A tibble: 20,496 x 3
   time_value geo_value  death_rate
 * <chr>      <date>          <dbl>
 1 ak         2020-12-31      0.158
 2 al         2020-12-31      0.438
 3 ar         2020-12-31      1.27 
 4 as         2020-12-31      0    
 5 az         2020-12-31      1.10 
 6 ca         2020-12-31      0.751
 7 co         2020-12-31      0.649
 8 ct         2020-12-31      0.819
 9 dc         2020-12-31      0.601
10 de         2020-12-31      0.807
# ... with 20,486 more rows
# i Use `print(n = ...)` to see more rows
Browse[1]> 
```

**Comment by dajmcdon** [comment]
Wow! Nice catch. What a strange behaviour.

**Comment by rachlobay** [comment]
Great! Thanks for posting the above comments. They definitely help! But it is probably best to address this from the root, if possible. 

Since the R CMD Check meltdown from using the most recent edition of epiprocess, Ken, Maggie, and I went through the merged pull requests from the past ~ two weeks (time frame’s based on when the Github versions of epipredict and epiprocess were not having issues) and found that the most troublesome change is`[.epi_df`); the other pull requests that were merged seemed to be mostly updating tests or documentation in epiprocess (so unlikely to cause such a problem). Based on how epirocess behaves when `[.epi_df` is present vs absent, I think that`[.epi_df` is causing these problems (& I expect there’ll be more trouble from it in the future, so we'll refine as necessary).

I was looking into a couple of ways to fix the two types of error messages shown in the R CMD check by going through the `[.epi_df` code line by line & running the tests that Maggie and I were looking at yesterday… The simplest soln to fix both issues (without messing with the `new_epi_df` code) looks to be to go from `new_epi_df(tibble::as_tibble(res),…` --> `as_epi_df(res,…` in there. So basically we gotta remove the call to construct a new epi_df from scratch… And going for this change makes sense because sometimes `res` (the `epi_df` subset we’re getting out of `[.epi_df`) sometimes already has the `epi_df` class to begin with, and `as_epi_df` will call `new_epi_df` if it is necessary, else just return as is. When I make this change all looks to be well between the most recent versions of epipredict and epiprocess (if someone else wants to check they get they intended effects, please do).

Now, if we want to keep that & not change it to `as_epi_df`, I briefly looked into what we’d likely need to do to `new_epi_df`... Removing the three lines in there where column reordering occurs seems to fix the errors involving`parsnip::fit()` & that makes sense with what Maggie and I were seeing (the weird behaviour with var./col. ordering). Then, probably all we’d have to do to fix the other type of error messages is some manual column rearrangement in the tests, as Maggie was suggesting (because the columns of a new `epi_df` now wouldn't have a strict ordering anymore)... But I’d be more hesitant to go for this approach because I didn’t write that code that we’d be removing here (note that `new_epi_df` code is the original `as_epi_df` code) and maybe that ordering is there for a good reason that I am not considering.

**Comment by mgyliu** [comment]
Adding some notes from my discussion with Rachel for papertrail:

- `[.epi_df` gets called multiple times through `parsnip::fit` 
- [These lines](https://github.com/cmu-delphi/epiprocess/blob/main/R/epi_df.R#L155-L158) in `epi_df.R:new_dpi_df` seem to do some column reordering, which could be part of the problem. I ran a debugger in here and those lines of code seem to reorder columns correctly. But good to keep this part of the code in mind for a future fix.
- Current fix is to change `new_epi_df(tibble::as_tibble(res),…` --> `as_epi_df(res,…` which Rachel and I agree is a good solution for now.

**Comment by rachlobay** [comment]
As Logan and I were talking about yesterday, it may also be good to look into what lines in `parsnip::fit()` are conflicting with the couple of problematic lines of code in `new_epi_df()`, because it is definitely possible that there could be problems cropping up from this in the future... I'll post an issue, but it is probably not urgent to get to as I think that we have more pressing problems to deal with right now.

**Comment by dajmcdon** [comment]
I messed around with this a bit yesterday. The (first?) specific issue (using the example in my check) is:

1. In `epi_shift_single()`, line 35 in my code: `dplyr::select(tidyselect::all_of(c(key_cols, col)))`.
2. The result of this line switches the NAMES `time_value` and `geo_value` for some reason. The result being that `time_value` then contains `<chr>` data with states while `geo_value` contains the dates.
3. Trying to add an integer `shift_val` to the character bombs.

**Comment by dajmcdon** [comment]
Can @rachlobay or @mgyliu open a PR that makes the simple change?

**Comment by mgyliu** [comment]
To confirm, the simple change is just going from `new_epi_df(tibble::as_tibble(res),...` to `as_epi_df(res...` in `[.epi_df`? 
@rachlobay did you already have a branch with the change implemented? If not I'm happy to take it

**Comment by rachlobay** [comment]
Yeah. I got a branch with that change... I also want to simplify the `[.epi_df` code in this PR a bit as per feedback from Logan, so I'll field this one. Expect a PR to be up for this within the next few hours.
