### ISSUE TITLE
Look into `parsnip::fit()` conflict with `new_epi_df()`?

### ISSUE THREAD

**Issue by rachlobay** [cmu-delphi/epipredict#111]
Look into what in `parsnip::fit()` conflicts with `new_epi_df()`. This problem should be apparent when `new_epi_df()` is used instead of `as_epi_df()` in `[.epi_df` from epiprocess and likely has to do with the couple of lines of column reordering code in `new_epi_df()`. This is related to Issue #104, but is lower priority as it is not likely to cause issues at present, but may be a problem for us in the future.

Example:
```
library(dplyr)
library(recipes)
library(parsnip)

jhu <- case_death_rate_subset %>%
  filter(time_value > "2021-11-01", geo_value %in% c("ak", "ca", "ny"))

r <- epi_recipe(jhu) %>%
  step_epi_lag(death_rate, lag = c(0, 7, 14)) %>%
  step_epi_ahead(death_rate, ahead = 7) %>%
  step_naomit(all_predictors()) %>%
  step_naomit(all_outcomes(), skip = TRUE)

wf <- epi_workflow(r, linear_reg()) %>% parsnip::fit(jhu) 
```

Resulting error:
```
Error in `dplyr::mutate()`:
! Problem while computing `time_value = time_value + shift_val`.
Caused by error in `time_value + shift_val`:
! non-numeric argument to binary operator
```

**Comment by dajmcdon** [comment]
Reposting from #104 

I messed around with this a bit yesterday. The (first?) specific issue (using the example in my check) is:

1. In epi_shift_single(), line 35 in my code: dplyr::select(tidyselect::all_of(c(key_cols, col))).
2. The result of this line switches the NAMES time_value and geo_value for some reason. The result being that time_value then contains <chr> data with states while geo_value contains the dates.
3. Trying to add an integer shift_val to the character bombs.
