### ISSUE TITLE
`args_list` `forecast_date` and `target_date`: assertion for `Date` type

### ISSUE THREAD

**Issue by mgyliu** [cmu-delphi/epipredict#126]
While using `arx_args_list`, wasn't immediately clear to me that `forecast_date` and `target_date` have to be `Date` types, and won't work correctly if it's a string like "2022-08-08". If it's not a `Date`, it gives this warning
```
Warning message:
Incompatible methods ("<.vctrs_vctr", "<.Date") for "<" 
```
which comes from [`layer_add_forecast_date.R#L85`](https://github.com/cmu-delphi/epipredict/blob/172ab1e8352d7d16e8b9f5c581f3ccd3c921734c/R/layer_add_forecast_date.R#L85) 

Proposed change is to either
- update documentation to make argument type known and clear
- change code to throw a readable error earlier if the user gives a non-`Date`
- or both?

**Comment by dajmcdon** [comment]
We should check in `flatline_args_list` that those are date type (or coercible to). Same for `are_args_list`.
