### ISSUE TITLE
Argument brainstorm

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#17]
Forecasters we've used/written have many arguments. Where would these fit in our framework? Please add to [the list](https://docs.google.com/document/d/1hQg9cZied8lW6DqOKqHeQ2qrJf4HOLWJoUzOYn9s-vU/edit#bookmark=id.n617orxwaulb) if you have a chance. 

We're especially concerned about major omissions.

**Comment by brookslogan** [comment]
I've added some brainstorming to [these notes](https://docs.google.com/document/d/1hQg9cZied8lW6DqOKqHeQ2qrJf4HOLWJoUzOYn9s-vU/edit#heading=h.htxiwesijgkn) and tried to simplify and add to [the list](https://docs.google.com/document/d/1hQg9cZied8lW6DqOKqHeQ2qrJf4HOLWJoUzOYn9s-vU/edit#bookmark=id.n617orxwaulb).
