### ISSUE TITLE
`arx_forecaster()`: `symmetrize` arg isn't used if we use `quantile_reg`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epipredict#170]
It would be nice to have an error message if the user requests symmetrization in this case (a bit tricky if `symmetrize = TRUE` remains the default), or to do something to symmetrize.

**Comment by dajmcdon** [comment]
Interesting. I suspect, realistically, the documentation should simply state that this applies to other forecasters. Would one ever want this in `quantile_reg()`? (I mean maybe we don't really want it ever, and should make the default FALSE).

**Comment by brookslogan** [comment]
I can't think of a reason to try to symmetrize coupled with `quantile_reg()`.  Doc update sounds good.  (Or alternatively, `symmetrize = FALSE` by default for everything (breaking change), and error if using `symmetrize = TRUE` with `quantile_reg()`.)
