### ISSUE TITLE
Rename or remove current `time_value` output column in predictions

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epipredict#188]
The current `time_value` output column indicates the index `time_value` used to define the test instance for each time series, but that's probably not as useful as (a) it being the target time, so we can easily join back with ground truth data, maybe apply some `epi_df` plotting tools, etc., or (b) the forecast date, because that'd also probably feel a bit more natural.  We should use a more descriptive name or eliminate this column altogether.

**Comment by dajmcdon** [comment]
closed by #200
