### ISSUE TITLE
`epi_archive` to pure S3

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epipredict#235]
Not sure if this exists as an issue or only in people's head, but it was an OKR that seems like its been hanging around. Seems like there was not useful overhead that arose from R6 that people wanted to ditch.
The specific summer OKR item was
> Move epi_archive from R6+S3 to S3 only, encapsulate fields, add filter method
which seems like several issue to me

**Comment by dajmcdon** [comment]
@dsweber2 This is an `epiprocess` issue not `epipredict`. Can you move there?

**Comment by dsweber2** [comment]
Right, that does make more sense of why I couldn't find it. There's an outstanding issue there: https://github.com/cmu-delphi/epiprocess/issues/340.
