### ISSUE TITLE
Implement function to grab the most recent data, sufficient for prediction

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#26]
For example, if we have `max_lag = 14`, then we would do something like:

```r
x_latest <- x %>%
  filter(!is.na(case_rate), !is.na(death_rate)) %>%
  group_by(geo_value) %>%
  slice_tail(n = 15) # have lag 0,...,14, so need 15 for a complete case
```

The function should read the `epi_recipe`, perhaps after `prep()` or `bake()`.

**Comment by ChloeYou** [comment]
I was wondering if I can I get some clarifications on this?

Would this function be a separate function stored in the arx_forecaster.R file? Additionally, would this function go somewhere before [line 44](https://github.com/cmu-delphi/epipredict/blob/e8cfd8e597e45114e8e1000085230dbff78e4616/R/arx_forecaster.R#L44)? or perhaps it should exist in  another file? 

Thank you in advance!

**Comment by ChloeYou** [comment]
new file, new function. get_target()/ get_test_data()
get recipe and get the data, and read the `ahead`

example: look at https://github.com/cmu-delphi/epipredict/blob/e8cfd8e597e45114e8e1000085230dbff78e4616/musings/example-recipe.R#L39

**Comment by ChloeYou** [comment]
Logan suggested taking a look at the following that included this operation:

cmu-delphi/covidcast/R-packages/modeltools

create_train_and_predict_matrices() although it had issues when dealing with data with nonzero reporting latency

**Comment by ChloeYou** [comment]
TO-DO: Add unit tests for this new function before creating a PR
