### ISSUE TITLE
add step_average

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epipredict#275]
After some discussion, we concluded that it would probably be worthwhile to implement something to enable simple 7 day averaging

**Comment by dsweber2** [comment]
should probably wait to see what happens in exploration-tooling with averaging

**Comment by dsweber2** [comment]
So apparently [`step_bs`](https://recipes.tidymodels.org/reference/step_bs.html) exists, along with all sorts of other spline methods; pairing with a `complete`, this would allow us to do way more sophisticated kinds of smoothing easily.

**Comment by dajmcdon** [comment]
See also the `step_epi_growth_rate()`. Though there's a bug there (it doesn't operate on test data correctly).
