### ISSUE TITLE
`print` implementations should not mix output to stdout and messages from `cli` functions

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epipredict#277]
E.g., mixing `cat` (printing to output stream) and `{cli}` functions ([issuing messages that knitr intercepts or] printing to message stream) in `print.epi_recipe` and `print.frosting` leads to some trouble with knitting documents. 

E.g., trying to rebuild forecast-framework.qmd in delphi-tooling book has this in a chunk with `#| collapse: true` earlier in the document for printing an `epi_recipe`:

```
#> ── Operations
#> 1.
#> Lagging: case_rate by 0, 7, 14 | Trained
#> 2.
#> Lagging: death_rate by 0, 7, 14 | Trained
#> 3.
#> Leading: death_rate by 7 | Trained
#> 4.
#> • Removing rows with NA values in: lag_0_case_rate, ... | Trained
#> 5.
#> • Removing rows with NA values in: ahead_7_death_rate | Trained
#> 6.
#> • # of recent observations per key limited to:: Inf | Trained
```

or, when printing a frosting with some other set of options:

![2023-12-15-023636_759x588_scrot](https://github.com/cmu-delphi/epipredict/assets/24498353/72c9d6b9-58dc-4407-aa60-43a57f8dae79)

It also messes with `capture.output`, which only captures one stream at a time (ordering is lost).

Potential fixes:
- See if `cat` can print to message stream via `file` argument.
- Replace `cat` with something like `cli::cli_text` with appropriate escaping/interpolation of programmatically-constructed/user-input/etc. strings, if it outputs in an acceptable format.

**Comment by brookslogan** [comment]
Workaround for `capture.output`:
```r
with_message_in_stdout <- function(code) {
  sink(stdout(), type = "message")
  on.exit({
    sink(type = "message")
  })
  code
}

capture.output(with_message_in_stdout(print(extract_recipe(out_gb$epi_workflow))))
#> ...
#> [14] "1. Lagging: case_rate by 0, 7, 14 | Trained"                                  
#> ...
```

But this doesn't seem to fix the qmd/knitr issues; in this context, the streams still appear to be separate, and `capture.output` can only capture one or the other at a time.

**Comment by brookslogan** [comment]
Workaround for .qmd:
```r
withCallingHandlers(print(extract_recipe(out_gb$epi_workflow)), message = function(m) {cat(m$message); tryInvokeRestart("muffleMessage")})
```

**Comment by dajmcdon** [comment]
I've tried dealing with this in various ways in the past. The version in `{recipes}` was somewhat recently [updated](https://github.com/tidymodels/recipes/pull/1072) but `{workflows}` still mixes: https://github.com/tidymodels/workflows/blob/main/R/workflow.R. 

A while back I'd found an open issue for this problem (cli resulting in breaks via knitr html) in one of the tidy packages, but I can't find it now.

**Comment by dajmcdon** [comment]
@rachlobay This happens in your #274 as well.
