### ISSUE TITLE
bug: severe latency forecasting warning not displaying

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epipredict#322]
_Originally posted by @dajmcdon in https://github.com/cmu-delphi/epipredict/pull/319#discussion_r1567551994_

There is supposed to be a warning when you try to train and forecast on data with a severe latency, but it has stopped showing up. Investigate and bring back?

**Comment by dsweber2** [comment]
I'm not sure that actually exists yet, as latency "doesn't exist" at the moment. I'm adding one in `step_adjust_latency`, but that's not on dev yet

**Comment by dshemetov** [comment]
Take a look at that comment, there's some text in the vignettes that comments on such a warning, maybe I misunderstood, but that warning is not showing up for the same code anymore 🤷

**Comment by dajmcdon** [comment]
I removed that warning, because it was annoying. All it did was _always_ warn if the `epi_df` had `as_of < today()`.

**Comment by dshemetov** [comment]
Oh that makes sense. I figured it checked if `as_of < today() - 90` or something. Is a warning with a better threshold something we want in principle or should we just scrap this?

**Comment by dajmcdon** [comment]
I think scrap it completely. The print methods will show all this information.
