### ISSUE TITLE
post_residual_quantiles

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#37]
create a post-processing step that creates residual quantiles

**Comment by ChloeYou** [comment]
- [ ] implement functions
- [ ] add roxygen description
- [ ] examples in roxygen description
- [ ] unit tests

**Comment by ChloeYou** [comment]
Side note, the function documentation for https://github.com/cmu-delphi/epipredict/blob/8bd7d4ab0efbd7a719529e544e441f707894fa7b/R/residual_quantiles.R can be a bit more detailed?
