### ISSUE TITLE
step/post_population_scaling

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#40]
Add a preprocessor/postprocessor that performs population scaling. Likely needs pop data somewhere in the package also allow for a column in the train/test data.

**Comment by ChloeYou** [comment]
Idea of population scaling and how the function works:

For example, in the `epi_df` dataset, there is a `case` count for each state. However, the user has an external dataset that contains information of population size in each state. The user would like to predict case rate by state, therefore in the preprocessing stage (`step_population_scaling`), the function should be able to do the following:
```{r}
r <- epi_recipe(x) %>%
  step_epi_ahead(death_rate, ahead = 7)  %>%
  step_epi_lag(death_rate, lag = c(0,7,14)) %>%
  step_epi_naomit() %>%
  step_population_scaling(x = df, geo_value = "state")
```
where `df` is the dataframe that the user provided with the population level data, and will require one of the columns of the dataframe to be named as "state" or "State". Currently, let's set the available values of the `geo_value` parameter to `c("state","county")`. Once the function reads in the parameters, it'll create a new column in the dataset and left join based on values in `geo_value` in the `epi_df`.

**Comment by ChloeYou** [comment]
cont'd...

For the prediction and postprocessing steps:
User should be able to just call `layer_population_scaling` in the following way:
```{r}
f <- frosting() %>%
    layer_predict() %>%
    layer_naomit(.pred) %>% 
    layer_residual_quantile() %>%
    layer_population_scaling(col = "case")
```
where the model outcome was "case_rate" (case/population), but now we would want to convert the predicted outcome back into cases. So `layer_population_scaling(col = "case")` would add a new column "case" in the prediction dataset (or is there a way to retain the original column name from the recipe?), and match the geo_values (state in this case) that were used to calculate the case_rate, and revert back: `case <-  case_rate * population_value`


Question: what order should `layer_population_scaling`  be applied to? Does it matter? For example, should ` layer_residual_quantile()` be evaluated before it? How about other future layers?

**Comment by ChloeYou** [comment]
@dajmcdon See above for some thoughts on how the function works and the way to implement it. Would appreciate it a lot if you take a look at it and maybe poke some holes if possible :D 

Thank you!

**Comment by ChloeYou** [comment]
Meeting notes:
Preprocess, add new parameters to function
- join on multiple keys; group_by = county and age. 
- be able to join on whatever matches the column/geo_value of the epi_df
- match the argument of dplyr::join()
- in epi_df, which column to scale, and the new column name should be
- add option to overwrite old column.
- in provided data, need to know which columns provide the population data.
