### ISSUE TITLE
get_test_data() should return an ungrouped epi_df

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#45]
1. Ensure that the result of `get_test_data()` in ungrouped.
2. Add a test to check that this is true.

**Comment by ChloeYou** [comment]
@dajmcdon do you mean to ungroup by geo_value?

**Comment by ChloeYou** [comment]
I'll fix this right away! What kind of downstream issues would it cause, just curious?

**Comment by dajmcdon** [comment]
Yes, exactly. Currently, the object that comes out is a grouped `epi_df` and it needs to be ungrouped.

(Also, it should really be grouped/sliced by geo_value and any `additional_metadata$other_keys`. You can use `epi_keys()` to grab the keys.)

Downstream, the grouping can break the more complicated behaviours needed at prediction time when you start doing the postprocessing. The grouping gums it up (hard for me to explain).

**Comment by ChloeYou** [comment]
I see. Thanks for explaining! I'll change the grouping as well then.

**Comment by ChloeYou** [comment]
@dajmcdon I don't think time_value should be included in the grouping right? or else the slice_tail is also grouped by time value.
