### ISSUE TITLE
`make_predictions` uses faulty `test_time_value` when using `epix_slide`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epipredict#50]
(`make_predictions`, `arx_forecaster`, `epix_slide`) don't work together quite correctly:

`make_predictions` takes a given `ref_time_value` (= target date), fetches the data `$as_of` that target date, but then doesn't pass that target date through to `make_predictions`; instead, `make_predictions` assumes that the `test_time_value` is the latest `time_value` with data available, which is rarely the case: we typically work off of data with some nonzero latency (or maybe, off of some point forecasts with negative latency).  So we end up with forecasts for `ref_time_values + ahead - minimum_latency_among_signals`, but labeled as forecasts for `ref_time_values + ahead`.

`epix_slide` might need updated to pass along the ref time value if it doesn't allow that already.

**Comment by dajmcdon** [comment]
Marking this wontfix but leaving open. The intention is to deprecate `make_predictions()` and rewrite the forecaster using the recipe framework. We can revisit at that time.

**Comment by dajmcdon** [comment]
Perhaps addressed by #55 .
