### ISSUE TITLE
Turn "musings" into a vignette

### ISSUE THREAD

**Issue by rachlobay** [cmu-delphi/epipredict#57]
As Daniel noted, it would be useful to turn the “musings” into a vignette, including post-processing.

**Comment by kenmawer** [comment]
I'll work on this, especially as I have used the example_recipe for testing.

**Comment by kenmawer** [comment]
I updated this in the newest pull request, although this is a messy pull request with several different changes. Also, I haven't fully checked about whether it runs properly, as I just copy-pasted the whole code into vignettes with just a few changes.

**Comment by dajmcdon** [comment]
@kenmawer I'm going to add you back here. Can you put it in a separate branch please (outside of other things)?
